import serial, time

a=serial.Serial('/dev/ttyUSB0',baudrate=9600,bytesize=8,parity='N',timeout=None,xonxoff=False,stopbits=1)
a.write('\r*cls\r*idn?\r')
time.sleep(0.5)
print a.read(a.inWaiting())
a.write('*rst\r')
time.sleep(0.5)
a.write('syst:zch on\r')
time.sleep(0.5)
a.write('curr:rang 2e-9\r')
time.sleep(0.5)
a.write('init\r')
time.sleep(0.5)
a.write('syst:zcor:acq\r')
time.sleep(0.5)
a.write('syst:zcor on\r')
time.sleep(0.5)
a.write('curr:rang:auto on\r')
time.sleep(0.5)
a.write('syst:zch off\r')
time.sleep(0.5)
a.write('form:elem read\r')
time.sleep(0.5)
while True:
    a.write('read?\r')
    time.sleep(0.5)
    print a.read(a.inWaiting())
    time.sleep(0.5)
